apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-nginx-deploy
spec:
    selector:
        matchLabels:
            app: my-nginx-deploy
    template:
        metadata:
            labels:
                app: my-nginx-deploy
        spec:
            containers:
                - name: my-nginx-deploy
                  image: nginx
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: my-nginx-service
spec:
    selector:
        app: my-nginx-deploy
    ports:
        - port: 80
          targetPort: 80
